Rem TO FIND FACTORIAL OF N NUMBERS USING FOR AND NEXT LOOP STATEMENT
Input "INPUT THE NUMBER "; N
F = 1
For R = 1 To N Step 1
    F = F * R
Next R
Print "FACTORIAL OF GIVEN NUMBER ";N;" IS "; F
End

