Rem TO FIND THE ROOTS OF QUADRATIC EQUATIONS
Input "ENTER VALUE OF FIRST CONSTANT ACCOMPANYING X^2 "; A
Input "ENTER THE VALUE OF SECOND CONSTANT ACCOMPANYING X "; B
Input " ENTER THE VALUE OF THIRD CONSTANT "; C
If A = 0 Then Print "EQN IS LINEAR" Else GoTo 10
ROOT = (-C) / B
Print "ROOT"; ROOT
GoTo 70
10 Let D = (B ^ 2) - (4 * A * C)
Print "DISCRIMINANT"; D
If D < 0 Then Print "ROOTS ARE IMAGINARY" Else GoTo 20
REAL = (-B / (2 * A))
IMAGINARY = Sqr(-D) / (2 * A)
Print "ROOT1 "; REAL; "+I"; IMAGINARY
Print "ROOT2 "; REAL; "-I"; IMAGINARY: GoTo 70
20 If D = 0 Then Print "REAL AND EQUAL ROOTS " Else GoTo 30
ROOT1 = (-B) / (2 * A)
ROOT2 = ROOT1
Print "ROOT1 AND ROOT2 ARE EQUAL TO "; ROOT1: GoTo 70
30 If D > 0 Then Print "REAL AND UNEQUAL ROOTS "
ROOT1 = (-B + Sqr(D)) / (2 * A)
ROOT2 = (-B - Sqr(D)) / (2 * A)
Print "ROOT1 IS "; ROOT1
Print "ROOT2 IS "; ROOT2
70 END
