Rem USE OF ON.. GOTO STATEMENT FOR ARITHMETIC OPERATIONS
Input "ENTER THE FIRST NUMBER "; A
Input "ENTER THE SECOND NUMBER "; B
Print "1. ADDITION"
Print "2. SUBTRACTION"
Print "3. MULTIPLICATION'"
Print "4. DIVISION"
Print "5. EXPONENTIATION"
Input "ENTER THE CHOICE "; C
On C GOTO 10, 20, 30, 40, 50
10 R = A + B: GoTo 60
20 R = A - B: GoTo 60
30 R = A * B: GoTo 60
40 R = A / B: GoTo 60
50 R = A ^ B: GoTo 60
60 Print "THE RESULT IS "; R
END
