Rem USE OF FOR.. NEXT LOOP
Rem TO FIND THE SUM OF N NATURAL NUMBERS
INPUT "ENTER THE NUMBER UPTO WHICH SUM IS OPTED ";N
S = 0
For I = 1 To N
    S = S + I
Next I
Print "SUM OF "; N; " NUMBERS IS "; S
End

